config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
   }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:index, :show]
  root to: "targets#index"
  resources :targets
  resources :messages
  resources :shares do
    resources :sharecomments, only: [:create]
  end
  resources :questions do
    resources :questioncomments, only: [:create]
  end
  resources :healths
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/health.rb
class Health < ActiveRecord::Base
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user, optional: true
  belongs_to_active_hash :question1
  belongs_to_active_hash :question2
  belongs_to_active_hash :question3
  belongs_to_active_hash :question4
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :questioncomments
end

app/models/question1.rb
class Question1 < ActiveHash::Base
  self.data = [
    {id: 1, anser: 'はい'}, {id: 2, anser: 'いいえ'},
]

end

app/models/question2.rb
class Question2 < ActiveHash::Base
  self.data = [
    {id: 1, anser: '2時間〜4時間'}, {id: 2, anser: '4時間〜6時間'}, {id: 3, anser: '6時間〜8時間'},
    {id: 4, anser: '8時間〜10時間'},{id: 5, anser: '4時間〜6時間'},
]
  include ActiveHash::Associations
  has_many :healths
end

app/models/question3.rb
class Question3 < ActiveHash::Base
  self.data = [
    {id: 1, anser: 'とても良い'}, {id: 2, anser: 'やや良い'}, {id: 3, anser: 'どちらとも言えない'},
    {id: 4, anser: 'やや悪い'},{id: 5, anser: 'とても悪い'},
]
  include ActiveHash::Associations
  has_many :healths
end

app/models/question4.rb
class Question4 < ActiveHash::Base
  self.data = [
    {id: 1, anser: 'とても高い'}, {id: 2, anser: 'やや高い'}, {id: 3, anser: 'どちらとも言えない'},
    {id: 4, anser: 'やや低い'},{id: 5, anser: 'とても低い'},
]
  include ActiveHash::Associations
  has_many :healths
end

app/models/questioncomment.rb
class Questioncomment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  has_many :sharecomments
end

app/models/sharecomment.rb
class Sharecomment < ApplicationRecord
  belongs_to :user
  belongs_to :share
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :targets
  has_many :questions
  has_many :queestioncomments 
  has_many :shares
  has_many :sharecomments 

  def self.guest
    find_or_create_by(email: "test@com") do |user|
      user.password = Rails.application.secrets.test_account_pass
      user.username = "guestuser"
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @date = DateTime.now.strftime("%m月%d日")
    @users = User.all
  end

  def new 
    @question = Question.new
    @date = DateTime.now.strftime("%m月%d日")
    @users = User.all
  end

  def create
    Question.create(question_params)
    redirect_to questions_path
  end

  def show
    @date = DateTime.now.strftime("%m月%d日")
    @users = User.all
    @question = Question.find(params[:id])
    @questioncomment = Questioncomment.new
    @questioncomments = @question.questioncomments.includes(:user)
  end

  private
  def question_params
    params.require(:question).permit(:title).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/questions/index.html.haml
= render 'targets/headcontent'
.maincontent
  = render 'targets/leftcontent'
  .question-index
    = link_to new_question_path, class: "questionlink" do
      質問を投稿はこちらから
      %i.fa.fa-hand-o-left
    .questioncontent
      - @questions.each do |q|
        .questiontext
          質問内容:
          =q.title
        .questionbox1
          .questionuser
            %i.fa.fa-user
            ユーザー名:
            =q.user.username
            さん  
          .questionday
            投稿した日付:
            =q.created_at
          .question-comment
            = link_to question_path(q) do
              %i.fas.fa-comment-alt :コメントする

app/views/questions/new.html.haml
= render 'targets/headcontent'
.maincontent
  = render 'targets/leftcontent'
  .question-box
    .question-new
      ー質問投稿ページー
    .question-new-box
      = form_with model: @question, local: true do |f|
        %ul 
          %li
            =f.text_area :title, class: 'target-box'
          %li  
            =f.submit '投稿する', class: 'target-sendbtn'

app/views/questions/show.html.haml
= render 'targets/headcontent'
.maincontent
  = render 'targets/leftcontent'
  .question-show
    .question-show-content
      質問内容：
      =@question.title
      .question-container
        = form_with(model: [@question, @questioncomment], local: true, id: "new_questioncomment") do |f|
          = f.text_area :text, placeholder: "コメントする", class: "question-textbox"
          = f.submit "投稿する", class: "question-submit"
      .questioncomments
        %h4 ＜コメント一覧＞
        - if @questioncomments
          - @questioncomments.each do |comment|
            %p
              %strong
                = link_to comment.user.username, "/users/#{comment.user_id}"
                ：
              = comment.text