config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
   }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:index, :show]
  root to: "targets#index"
  resources :targets
  resources :messages
  resources :shares do
    resources :sharecomments, only: [:create]
  end
  resources :questions do
    resources :questioncomments, only: [:create]
  end
  resources :healths
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/health.rb
class Health < ActiveRecord::Base
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user, optional: true
  belongs_to_active_hash :question1
  belongs_to_active_hash :question2
  belongs_to_active_hash :question3
  belongs_to_active_hash :question4
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :questioncomments
end

app/models/question1.rb
class Question1 < ActiveHash::Base
  self.data = [
    {id: 1, anser: 'はい'}, {id: 2, anser: 'いいえ'},
]

end

app/models/question2.rb
class Question2 < ActiveHash::Base
  self.data = [
    {id: 1, anser: '2時間〜4時間'}, {id: 2, anser: '4時間〜6時間'}, {id: 3, anser: '6時間〜8時間'},
    {id: 4, anser: '8時間〜10時間'},{id: 5, anser: '4時間〜6時間'},
]
  include ActiveHash::Associations
  has_many :healths
end

app/models/question3.rb
class Question3 < ActiveHash::Base
  self.data = [
    {id: 1, anser: 'とても良い'}, {id: 2, anser: 'やや良い'}, {id: 3, anser: 'どちらとも言えない'},
    {id: 4, anser: 'やや悪い'},{id: 5, anser: 'とても悪い'},
]
  include ActiveHash::Associations
  has_many :healths
end

app/models/question4.rb
class Question4 < ActiveHash::Base
  self.data = [
    {id: 1, anser: 'とても高い'}, {id: 2, anser: 'やや高い'}, {id: 3, anser: 'どちらとも言えない'},
    {id: 4, anser: 'やや低い'},{id: 5, anser: 'とても低い'},
]
  include ActiveHash::Associations
  has_many :healths
end

app/models/questioncomment.rb
class Questioncomment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  has_many :sharecomments
end

app/models/sharecomment.rb
class Sharecomment < ApplicationRecord
  belongs_to :user
  belongs_to :share
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :targets
  has_many :questions
  has_many :queestioncomments 
  has_many :shares
  has_many :sharecomments 

  def self.guest
    find_or_create_by(email: "test@com") do |user|
      user.password = Rails.application.secrets.test_account_pass
      user.username = "guestuser"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/_headcontent.html.haml
.top
  .topcontent
    = @date
    の目標
  .topleft
    %ul
      %li
      = link_to shares_path, class: "share" do
        %i.fa.fa-share-alt
        共有
      %li
      = link_to questions_path, class: "question" do
        %i.fa.fa-question
        質問
      %li
      = link_to new_message_path, class: "target" do
        %i.fa.fa-check-square
        本日の目標投稿
      %li
      = link_to new_group_path, class: "newgroup" do
        %i.fa.fa-group
        新規グループ作成
    = link_to 'root', class: "condition" do
      %i.fa.fa-heartbeat
      体調管理報告
  .topuser
    - if user_signed_in?
      = link_to edit_user_registration_path, class: 'profilebtn' do
        %i.fa.fa-edit
        プロフィール変更
      = link_to destroy_user_session_path, method: :delete, class: 'logoutbtn' do
        %i.fa.fa-sign-out
        ログアウト
    - else
      = link_to '・サインアップ', new_user_registration_path, class: 'signupbtn'
      = link_to '・ログイン', new_user_session_path, class: 'loginbtn'

app/views/messages/new.html.haml
= render 'headcontent'
.maincontent
  = render 'leftcontent'
  .rightcontent
    .rightcontent-text
      = form_with model: @target do |f|
        %ul 
          %li
            =f.text_field :title, class: 'target-box'
          %li  
            =f.submit '投稿する', class: 'sendbtn'