config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
   }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:index, :show]
  root to: "targets#index"
  resources :targets
  resources :messages
  resources :shares do
    resources :sharecomments, only: [:create]
  end
  resources :questions do
    resources :questioncomments, only: [:create]
  end
  resources :healths
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/health.rb
class Health < ActiveRecord::Base
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user, optional: true
  belongs_to_active_hash :question1
  belongs_to_active_hash :question2
  belongs_to_active_hash :question3
  belongs_to_active_hash :question4
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :questioncomments
end

app/models/question1.rb
class Question1 < ActiveHash::Base
  self.data = [
    {id: 1, anser: 'はい'}, {id: 2, anser: 'いいえ'},
]

end

app/models/question2.rb
class Question2 < ActiveHash::Base
  self.data = [
    {id: 1, anser: '2時間〜4時間'}, {id: 2, anser: '4時間〜6時間'}, {id: 3, anser: '6時間〜8時間'},
    {id: 4, anser: '8時間〜10時間'},{id: 5, anser: '4時間〜6時間'},
]
  include ActiveHash::Associations
  has_many :healths
end

app/models/question3.rb
class Question3 < ActiveHash::Base
  self.data = [
    {id: 1, anser: 'とても良い'}, {id: 2, anser: 'やや良い'}, {id: 3, anser: 'どちらとも言えない'},
    {id: 4, anser: 'やや悪い'},{id: 5, anser: 'とても悪い'},
]
  include ActiveHash::Associations
  has_many :healths
end

app/models/question4.rb
class Question4 < ActiveHash::Base
  self.data = [
    {id: 1, anser: 'とても高い'}, {id: 2, anser: 'やや高い'}, {id: 3, anser: 'どちらとも言えない'},
    {id: 4, anser: 'やや低い'},{id: 5, anser: 'とても低い'},
]
  include ActiveHash::Associations
  has_many :healths
end

app/models/questioncomment.rb
class Questioncomment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  has_many :sharecomments
end

app/models/sharecomment.rb
class Sharecomment < ApplicationRecord
  belongs_to :user
  belongs_to :share
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :targets
  has_many :questions
  has_many :queestioncomments 
  has_many :shares
  has_many :sharecomments 

  def self.guest
    find_or_create_by(email: "test@com") do |user|
      user.password = Rails.application.secrets.test_account_pass
      user.username = "guestuser"
    end
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def new
    @share = Share.new
    @date = DateTime.now.strftime("%m月%d日")
    @users = User.all
  end

  def create
    Share.create!(share_params)
    redirect_to shares_path
  end

  def index
    # @comments = @share.sharecomment.includes(:username)
    @shares = Share.all
    @date = DateTime.now.strftime("%m月%d日")
    @users = User.all
  end

  def show
    @users = User.all
    @date = DateTime.now.strftime("%m月%d日")
    @share = Share.find(params[:id])
    # @sharecomments = Sharecomment.find(params[:id])
    # @sharecomments = Sharecomment.all
    # @sharecomment = Sharecomment.new
    @sharecomment = Sharecomment.new
    @sharecomments = @share.sharecomments.includes(:user)
  end

  private
  def share_params
    params.require(:share).permit(:share).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shares/index.html.haml
= render 'targets/headcontent'
.maincontent
  = render 'targets/leftcontent'
  .share
    .rightcontent
      = link_to new_share_path, class: "sharelink" do
        新規共有はこちら
        %i.fa.fa-hand-o-left
      .sharebox
        - @shares.each do |s|
          .sharetext
            共有:
            =s.share
          .shareuser
            %i.fa.fa-user
            ユーザー名:
            =s.user.username
            さん  
          .shareday
            投稿した日付:
            =s.created_at
          .share-comment
            = link_to share_path(s) do
              %i.fas.fa-comment-alt :コメントする
          -# .container
          -#   = form_with(model: [@share, @sharecomment], local: true) do |form|
          -#     = form.text_area :text, placeholder: "コメントする", rows: "2"
          -#     = form.submit "SEND"

            

app/views/shares/new.html.haml
= render 'targets/headcontent'
.maincontent
  = render 'targets/leftcontent'
  .box
    .box-top
      ー新規共有ページー
    .box-text
      = form_with model: @share, local: true do |f|
        %ul 
          %li
            =f.text_area :share, class: 'target-box'
          %li  
            =f.submit '投稿する', class: 'target-sendbtn'

app/views/shares/show.html.haml
= render 'targets/headcontent'
.maincontent
  = render 'targets/leftcontent'
  .share-show
    .share-showcontent
      共有内容：
      =@share.share
      .share-container
        = form_with(model: [@share, @sharecomment], local: true, id: "new_sharecomment") do |f|
          = f.text_area :text, placeholder: "コメントする", class: "share-textbox"
          = f.submit "投稿する", class: "share-submit"
      .sharecomments
        %h4 ＜コメント一覧＞
        - if @sharecomments
          - @sharecomments.each do |comment|
            %p
              %strong
                = link_to comment.user.username, "/users/#{comment.user_id}"
                ：
              = comment.text